### ISSUE TITLE
Signature expired error

### ISSUE THREAD

**Issue by SachinGanesh** [labrixdigital/cloudwatch#1]
Hi, 

This package works fine, but after sometime it crashes:
```
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the DescribeLogStreams operation: Signature expired: 20220627T113444Z is now earlier than 20220627T130431Z (20220627T130931Z - 5 min.)

 File "/usr/local/lib/python3.6/dist-packages/cloudwatch/cloudwatch.py", line 55, in __init__
    response = self.logs.describe_log_streams(logGroupName=self.log_group)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 911, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

**Comment by ernestomi** [comment]
Hi Sachin,

`InvalidSignatureException` arises when the signature (which changes in each message logged onto the same stream) is out of synch. This happens typically when multiple processes are logging onto the same **stream**.

Are you running multiple processes on the same stream? I would first suggest to have each process of them create its own stream (on the same log group is fine).  The easiest way to do this is to allow the handler to create its own default log stream (by not specifying the log_stream) as follows:

```
handler = cloudwatch.CloudwatchHandler(log_group = 'my_log_group')
```

**Comment by ernestomi** [comment]
@SachinGanesh let us know if the above doesnt work and happy to re-open. In the meantime are closing the issue.

**Comment by SachinGanesh** [comment]
Hi, My application has multiple threads writing to the same logger. Will this be an issue?

**Comment by ernestomi** [comment]
Hi @SachinGanesh, it wont be an issue if you create one logger per thread, where the log_stream name is different per thread/logger. As I mentioned, you can acheive this if you DONT set the name of the log_stream.

Here is an example of something that worked for me:

```python3
import _thread
import time
import logging
from cloudwatch import cloudwatch

# Define a function for the logger creation
def get_logger(logger_name):
   #Create the logger 
   #(By passing a unique logger_name, you ensure a unique object)
   logger = logging.getLogger('{}-logger'.format(logger_name))
   #Create the formatter
   formatter = logging.Formatter('%(asctime)s : %(levelname)s - %(message)s')
   #Create the handler
   handler = cloudwatch.CloudwatchHandler(
    log_group = 'multithread_example'
   )
   #Pass the formater to the handler
   handler.setFormatter(formatter)
   #Set the level
   logger.setLevel(logging.INFO)
   #Add the handler to the logger
   logger.addHandler(handler)
   return logger

# Define a function for the thread
def print_time(thread_name, delay):
   #Create the logger
   logger = get_logger(thread_name)
   #The rest of the process
   count = 0
   while count < 5:
      time.sleep(delay)
      count += 1
      logger.info("{}: {}".format(thread_name, time.ctime(time.time()) ))

# Create two threads as follows
try:
   _thread.start_new_thread( print_time, ("Thread-1", 2, ) )
   _thread.start_new_thread( print_time, ("Thread-2", 4, ) )
except:
   print("Error: unable to start thread")

while 1:
   pass
```
<img width="1072" alt="Screenshot 2022-07-06 at 18 10 56" src="https://user-images.githubusercontent.com/14869713/177595924-876c4a61-db8a-402e-b3ce-14fd0f4bba05.png">

If your processes start at the same time, and there is no existing **"Log Group"**, you might get a `ResourceAlreadyExistsException`. In that case, its best to create the log group in advance, or separate slightly the processes. Note that we already have a ticket open to solve this case.
