### ISSUE TITLE
Deprecation notice upon installation

### ISSUE THREAD

**Issue by sabaimran** [labrixdigital/cloudwatch#6]
When installing via `pip install cloudwatch`, I get following error:
```
DEPRECATION: cloudwatch is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

pip version: `pip 23.0.1`
python version: `Python 3.11.4`

**Comment by ernestomi** [comment]
Hi @sabaimran,

Thanks for raising this issue, I have created a minor version upgrade (1.1.1) to fix this and is already released in PyPi. I have tested with the same pip and python versions and can no longer see the deprecation warning.

Please feel free to re-open the issue if you experience the deprecation warning again
